apiVersion: apps/v1
kind: Deployment
metadata:
  name: msa-deployment
  labels:
    name: msa
spec:
  replicas: 1
  selector:
    matchLabels:
      name: msa
  template:
    metadata:
      labels:
        name: msa
    spec:
      containers:
      - name: msa
        image: gsmdm/dockerjava:latest
        resources:
            limits:
              cpu: 500m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
        ports:
        - containerPort: 8686

---
apiVersion: v1
kind: Service
metadata:
  name: msa
  labels:
    name: msa
spec:
  type: NodePort
  ports:
    - port: 8686
      nodePort: 30092
      name: http
  selector:
    name: msa
